version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./back-end:/var/www/html
      - ./back-end/public:/var/www/html/public
    command: bash -c "chown -R www-data:www-data /var/www/html/storage && php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - todo-net
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=todo_db
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
    depends_on:
      - db

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3001:3000"
    volumes:
      - ./front-end:/app
      - /app/node_modules
      - /app/.next
    networks:
      - todo-net
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - NODE_ENV=production
    depends_on:
      - backend

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - todo-net
    ports:
      - "3306:3306"

networks:
  todo-net:
    driver: bridge

volumes:
  db-data:
    driver: local
